### ISSUE TITLE
SSR running into the mob cap.

### ISSUE THREAD

**Issue by jinks** [SgtPunishment/Soul-Shards-The-Old-Ways#11]
Heya,
my modpack (Hermitcraft Modsauce) recently updated from SSR 1.2 to RC3.1-B).
After a bit of playing the new version I noticed that there were essentially **no** hostile mobs spawning in the Overworld any more.

I mucked about with opis (kill/purge) and server settings for a while and in the end discovered that the culprit seems to be the new SSR.

I have 3 chunkloaded mobspawners in my base at the moment. If I turn those off, mob spawning returns to normal. It feels to me like the old SSR bypassed the mob cap while the new one doesn't.

Did something change in this regard? Could some code have gotten lost in the transition?

Note: I have not built new soul cages, so these are still in place from the previous version, could that be an issue?

**Comment by SgtPunishment** [comment]
You would have to ask Moze_Intel as he completely re-wrote the mod, all my team did was re-implement some of the changes we made (Achievements, In game editing of configs)
