### ISSUE TITLE
SSR Crash server

### ISSUE THREAD

**Issue by Keridos** [SgtPunishment/Soul-Shards-The-Old-Ways#12]
https://paste.ee/p/DAFvG

And did you maybe forget updating this repository with the newest source code?

**Comment by SgtPunishment** [comment]
What version of Forge are you using?, and I'm aware I forgot to update the source code

**Comment by Keridos** [comment]
Forge 1.7.10-10.13.2.1230

If you updated this, I wouldve already fixed this. I am 99% sure you forgot a @SideOnly(Side.CLIENT) in line 29 in the Cage_Block class.

**Comment by SgtPunishment** [comment]
That is certainly possible, but just in case this mod was compiled against Forge-1.7.10-10.13.2.1232

**Comment by Keridos** [comment]
The crash is absolutely clear about what happened, that has nothing to do with forge versions, did you even read the crash report?

**Comment by SgtPunishment** [comment]
Yes I did read the crash report, I am currently going through the code removing any other possible areas of a crash, and I do not appreciate the attitude, I was just explaining that I compiled the mod to a version NEWER than what you’re using as it COULD OF (Not saying it did) contributed towards the issue

**Comment by Keridos** [comment]
Found out what caused this. SideONly should be only the geticon and registerblock icon methods, the icons variable can even be initialised on the server.

And sorry if you felt insulted by me, did not want to anger you-

**Comment by SgtPunishment** [comment]
I didn't feel insulted, just annoyed just ignore me, it's late here in the uk
