### ISSUE TITLE
SSR Compatiblity Waila 1.5.8a

### ISSUE THREAD

**Issue by Keridos** [SgtPunishment/Soul-Shards-The-Old-Ways#13]
The SSRWailaProvider class still needs to implement getNBTData(net.minecraft.entity.player.EntityPlayerMP,net.minecraft.tileentity.TileEntity,net.minecraft.nbt.NBTTagCompound,net.minecraft.world.World,int,int,int).

**Comment by SgtPunishment** [comment]
We're using Waila 1.5.3, will update description.

**Comment by Keridos** [comment]
That might cause crashes with newer Waila versions. You should not force users to downgrade mods to be able to play this mod.

**Comment by SgtPunishment** [comment]
I'm not forcing anyone to downgrade, at the time of adding Waila Support (before christmas) any version above 1.5.3 at the time caused crashes or simply didn't work for us, but as I just updated the forum thread we will be looking into updating our waila support
