### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by InfinityRaider** [SgtPunishment/Soul-Shards-The-Old-Ways#22]
Not sure if you are aware of it or not, but SSTOW causes minecraft to crash in my heavily modded instance:
http://openeye.openmods.info/crashes/04d05b99b58a880d433349172a2875f8

**Comment by SgtPunishment** [comment]
It's an enchantment ID conflict, go into the SSTOW config folder and change the enchantment ID from 52 to another number.

**Comment by grydian** [comment]
Little tip InfinityRaider..  In the third section of your crash report it clearly says its an enchantment ID conflict.  Just check there next time before reporting a crash :)  Lots of mods use enchantments and unlike itemIDs these are still hard configured in 1.7.10

**Comment by InfinityRaider** [comment]
Omg my apologies, didn't even notice, I feel so dumb right now.

**Comment by SgtPunishment** [comment]
Infinity, it's alright, as grydain said it's hard coded (Even tho we did have a semi-working) work around to get the next available slot.

**Comment by grydian** [comment]
Hey man it happens to all of us :)
