### ISSUE TITLE
Soul Forge - Easily broken

### ISSUE THREAD

**Issue by psychofad** [SgtPunishment/Soul-Shards-The-Old-Ways#24]
The Soul Forge is completely destroyed if you simply punch it.  Using SSTOW-RC6-B.  It seems the block hardness is non-existent.  Using a pick will drop the block with the slightest tap, but using your hand destroys it like in creative mode.

**Comment by CorvusUrro** [comment]
I'll have a look into this

**Comment by SgtPunishment** [comment]
Thanks for bringing this to our attention, I honestly thought we fixed this in a past version, must of accidently deleted that line

**Comment by SgtPunishment** [comment]
Fixed in the latest RC7 update / code push
