### ISSUE TITLE
Fuel vanishing on relog

### ISSUE THREAD

**Issue by SgtPunishment** [SgtPunishment/Soul-Shards-The-Old-Ways#35]
Fuel in the soul forge vanish when saving and reloading worlds.

**Comment by UnstoppableN** [comment]
could not reproduce this issue

**Comment by SgtPunishment** [comment]
Try closing Minecraft and re opening

Sent from my Fire

On 25 March 2015, at 22:55, UnstoppableN <notifications@github.com> wrote:

could not reproduce this issue

**Comment by SgtPunishment** [comment]
Couldn't replicate rare bug
