### ISSUE TITLE
[Suggestions] Update the mod to 1.5.2 for add in ModPack

### ISSUE THREAD

**Issue by Hideman85** [SgtPunishment/Soul-Shards-The-Old-Ways#48]
The following project to update in 1.5.2 :
https://github.com/Hideman85/Soul-Shards-The-Old-Ways

Need Help :)

Thanks

**Comment by SgtPunishment** [comment]
I'm assuming you're trying to back-port it to 1.5.2? If so I'm not going to help with that as I'd have to re-learn all of the syntax and what not for an older version of the software
