### ISSUE TITLE
[Bug] Right click on mob spawner with soul shard crash

### ISSUE THREAD

**Issue by SunnyTD** [SgtPunishment/Soul-Shards-The-Old-Ways#50]
Crashes with both unspecified and specified sould shard. (ex: Blaze soul shard vs none)
Able to load game back up, and soul shard is unchanged. 

Log: http://pastebin.com/ZAiLY0pP

**Comment by TehNut** [comment]
Hm, I never did test that in an Obf environment. It appears that I'm calling an MCP name instead of the obfuscated name.

**Comment by TehNut** [comment]
Also, the correct place to report bugs is now [here](https://github.com/TehNut/Soul-Shards-The-Old-Ways/issues).

**Comment by TehNut** [comment]
Fixed with https://github.com/TehNut/Soul-Shards-The-Old-Ways/commit/0eb2499d50e6d7c550fe35a3d5cd72826dcb1a89
