### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by DnTheMn** [SgtPunishment/Soul-Shards-The-Old-Ways#52]
Issue Description: when crafting blank soul shards the diamond is not consumed. Also placing a shard into a spawner does not remove it from inventory so you can place a shard then remove it to make a copy.

Community sponge based server
Version of All the Mods:1.11

Added mods (Optifine, Fastcraft, etc.):

1.optifine
2.better fps

**Comment by TehNut** [comment]
1. Wrong repository. 
2. Attempt reproduction without Sponge. I do nothing weird.

**Comment by DnTheMn** [comment]
its not my server i was posting on behalf of someone else and whats the right repository so i know for the future

**Comment by TehNut** [comment]
https://github.com/TehNut/Soul-Shards-The-Old-Ways
