### ISSUE TITLE
No check if the mob is IEntityOwnable and owned

### ISSUE THREAD

**Issue by schindlershadow** [SgtPunishment/Soul-Shards-The-Old-Ways#54]
Players should not be able to make spawners of owned entities.

Entities spawned from a shard made of owned entities are not owned.

Proposed fixes:
1. no shard creation from owned entities
or
2. entities spawned from a shard made of owned entities should also be owned by the same owner.

fix #2 may cause issues for some mods.

**Comment by TehNut** [comment]
1. What version is this for?
2. This repository is dead. If this is an issue pertaining to Minecraft 1.10 or 1.11, please report it [here](https://github.com/TehNut/Soul-Shards-The-Old-Ways). Other Minecraft versions are unsupported.

**Comment by schindlershadow** [comment]
sorry about that 
https://github.com/TehNut/Soul-Shards-The-Old-Ways/issues/36
